/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedFilesRouteImport } from './routes/_authenticated/files'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as ApiAssistRouteImport } from './routes/api/assist'
import { Route as AuthenticatedMattersIndexRouteImport } from './routes/_authenticated/matters.index'
import { Route as AuthenticatedMattersIdRouteImport } from './routes/_authenticated/matters.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilesRoute = AuthenticatedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAssistRoute = ApiAssistRouteImport.update({
  id: '/api/assist',
  path: '/api/assist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMattersIndexRoute =
  AuthenticatedMattersIndexRouteImport.update({
    id: '/matters/',
    path: '/matters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMattersIdRoute = AuthenticatedMattersIdRouteImport.update({
  id: '/matters/$id',
  path: '/matters/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/files': typeof AuthenticatedFilesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/today': typeof AuthenticatedTodayRoute
  '/api/assist': typeof ApiAssistRoute
  '/matters/$id': typeof AuthenticatedMattersIdRoute
  '/matters/': typeof AuthenticatedMattersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/files': typeof AuthenticatedFilesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/today': typeof AuthenticatedTodayRoute
  '/api/assist': typeof ApiAssistRoute
  '/matters/$id': typeof AuthenticatedMattersIdRoute
  '/matters': typeof AuthenticatedMattersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/files': typeof AuthenticatedFilesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/api/assist': typeof ApiAssistRoute
  '/_authenticated/matters/$id': typeof AuthenticatedMattersIdRoute
  '/_authenticated/matters/': typeof AuthenticatedMattersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contacts'
    | '/files'
    | '/settings'
    | '/templates'
    | '/today'
    | '/api/assist'
    | '/matters/$id'
    | '/matters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contacts'
    | '/files'
    | '/settings'
    | '/templates'
    | '/today'
    | '/api/assist'
    | '/matters/$id'
    | '/matters'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/contacts'
    | '/_authenticated/files'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/_authenticated/today'
    | '/api/assist'
    | '/_authenticated/matters/$id'
    | '/_authenticated/matters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAssistRoute: typeof ApiAssistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/files': {
      id: '/_authenticated/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthenticatedFilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/assist': {
      id: '/api/assist'
      path: '/api/assist'
      fullPath: '/api/assist'
      preLoaderRoute: typeof ApiAssistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/matters/': {
      id: '/_authenticated/matters/'
      path: '/matters'
      fullPath: '/matters/'
      preLoaderRoute: typeof AuthenticatedMattersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matters/$id': {
      id: '/_authenticated/matters/$id'
      path: '/matters/$id'
      fullPath: '/matters/$id'
      preLoaderRoute: typeof AuthenticatedMattersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedFilesRoute: typeof AuthenticatedFilesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedMattersIdRoute: typeof AuthenticatedMattersIdRoute
  AuthenticatedMattersIndexRoute: typeof AuthenticatedMattersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedFilesRoute: AuthenticatedFilesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedMattersIdRoute: AuthenticatedMattersIdRoute,
  AuthenticatedMattersIndexRoute: AuthenticatedMattersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAssistRoute: ApiAssistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
